### PR TITLE
[ENH] Adding hybrid spaces for CIFTI use

### PR DESCRIPTION
**Pull request by chrisgorgo**
This will simplify handling CIFTI files and resolve the issue of hybrid spaces for the most common cases. Let me know what do you think @effigies @edickie

### CODE REVIEW

**Comment by edickie** [comment]
I dunno. There's still some issues.

1. Gifti files in hcp outputs have both volume and surface spaces (I.e. there are both T1w/32k meshes and MNI/32k meshes in HCP derivatives). 
2. The fact that the fsLR32k surfaces should. Be used with the greyordinate91k files is less intuitive.
3. If "greyordinate" is a lot of characters. If we do go in this direction I'm in favor or condensing it -'greyord'?

Also I think fsLR32k might be different (ish) from Conte69...but I'll look it up tomorrow.

**Comment by chrisgorgo** [comment]
On Tue, Mar 5, 2019 at 8:04 PM Erin W Dickie <notifications@github.com>
wrote:

> I dunno. There's still some issues.
>
>    1. Gifti files in hcp outputs have both volume and surface spaces
>    (I.e. there are both T1w/32k meshes and MNI/32k meshes in HCP derivatives).
>
> Did you mean CIFTI?


>
>    1. The fact that the fsLR32k surfaces should. Be used with the
>    greyordinate91k files is less intuitive.
>
> I thought the definition of 'greyordinate91k'  is clear about that. How
should I improve it?

>
>    1. If "greyordinate" is a lot of characters. If we do go in this
>    direction I'm in favor or condensing it -'greyord'?
>
> Sure that makes sense.

>
>
> Also I think fsLR32k might be different (ish) from Conte69...but I'll look
> it up tomorrow.
>
Yes it is different. What in this PR suggests otherwise?

**Comment by effigies** [comment]
In principle, I'm good with adding this table for tracking common hybrids. It would be nice to have a means of permitting arbitrary combinations that could be specified (I think there was talk at one point of a `spaces.tsv` or maybe `spaces.json` file), but if we cover the common cases now, we can let the custom stuff percolate in the community for a little bit before standardizing.

As to the specifics of these spaces, I defer to @edickie. I have extremely little practical experience with CIFTIs. I think @satra or @mgxd have been working with them more, though that might only be with fMRIPrep's super-non-standard CIFTI outputs.

**Comment by satra** [comment]
> fMRIPrep's super-non-standard CIFTI outputs.

i would not call them non-standard, they are completely valid CIFTI files. they are just not the HCP pipeline CIFTI outputs. 

i'm fine with adding these keys, i still do think there should be a `spaces.json` that provides additional details. having an additional file provides much more flexibility towards the future, as opposed to curating a fixed set of space keys.

i generally have no problem with a controlled vocabulary, but in this case you are soon going to run into the same issue that has brought up changes to the nifti specification for sform/qform codes.

**Comment by chrisgorgo** [comment]
My reasoning is the following:
- Most people will need support of `greyord91k` since it is the most popular hybrid space
- There is very little evidence showing that other types of hybrid spaces are being used out there. Even though FMRIPREP produces a different hybrid space I actually don't know if anyone is using it.
- We don't have anything in the current proposal preventing extending it to support any combination of surface/volume space

Thus maybe we should move on for now merge this and come up with a more flexible mechanism later.

**Comment by edickie** [comment]
On Tue, Mar 5, 2019 at 11:10 PM Chris Gorgolewski <notifications@github.com>
wrote:

> On Tue, Mar 5, 2019 at 8:04 PM Erin W Dickie <notifications@github.com>
> wrote:
>
> > I dunno. There's still some issues.
> >
> > 1. Gifti files in hcp outputs have both volume and surface spaces
> > (I.e. there are both T1w/32k meshes and MNI/32k meshes in HCP
> derivatives).
> >
> > Did you mean CIFTI?
>

Actually no, I meant GIFTI, it's the hard one. I have surfaces like:
<bids_root>_hemi-L_space-T1wLR32k_pial.surf.nii
   -> 32k vertices where the 3D coortidantes are in space-T1w
   -> overlays on the `<bidsroot>_desc-preproc_T1w.nii.gz` image)
< bids_root>_hemi-L_space-MNILR32k_pial.surf.nii
  -> 32k vertices where the 3D coordinates are in space-MNI
  -> overlays on the `<bidsroot>_space-MNI_desc-preproc_T1w.nii.gz` image
There is also CIFTI files (containing thickness or cortical atlas
parcellations) that don't have a subcortical data, and they can be
overlayed/used in conjunction with *both *the
space-T1wLR32k_pial.surf.nii space-MNILR32k_pial.surf.nii surfaces.
These are probably better mapped to space-fsLR32k.

The truth is that these are getting super complicated and probably merit
more required subfields in a spaces.json (or sidecar.json) file. (Rather
than trying to have a restricted spaces key-value pair for all of these
different combinations of 2D and 3D space that can exist in GIFTI and CIFTI
files).

I think the definition of greyord91k space is well written. I'm just a
little sad that the relationship between greyord91k and fsLR32k (i.e. the
fact that they in the same space/can be used together), will not be
immediately intuitive to a new user (unless they read an appendix to the
BIDS spec). Raw bids and fmriprep outputs have always warranted that "oh I
get it :-)" response from new users. But maybe I just need to swallow the
idea that CIFTI files will always be f*ing complicated for new users.

The greyord91k explanation made me realize that CIFTI files can also differ
in the way that subcortical data represented. Which I think requires a new
key `SubcorticalAtlas` (?) within the json sidecar.

My student and I are working on this spreadsheet
https://docs.google.com/spreadsheets/d/1uJKQWoqGFD0FJE8Tm9hQVFj2-xOgo5zN1dO-ALwkT0M/edit?usp=sharing
to map these outputs... Dunno if it helps..

**Comment by edickie** [comment]
Honestly, I think more in favour of greyord91k files being referred to as
space-fsLR32k (or MNIfsLR32k) than greyord91k... with the rest of the info
specified in the .json...

**Comment by chrisgorgo** [comment]
> Actually no, I meant GIFTI, it's the hard one. I have surfaces like:
<bids_root>_hemi-L_space-T1wLR32k_pial.surf.nii
   -> 32k vertices where the 3D coortidantes are in space-T1w
   -> overlays on the `<bidsroot>_desc-preproc_T1w.nii.gz` image)
< bids_root>_hemi-L_space-MNILR32k_pial.surf.nii
  -> 32k vertices where the 3D coordinates are in space-MNI
  -> overlays on the `<bidsroot>_space-MNI_desc-preproc_T1w.nii.gz` image
There is also CIFTI files (containing thickness or cortical atlas
parcellations) that don't have a subcortical data, and they can be
overlayed/used in conjunction with *both *the
space-T1wLR32k_pial.surf.nii space-MNILR32k_pial.surf.nii surfaces.
These are probably better mapped to space-fsLR32k.

I agree.

> Honestly, I think more in favour of greyord91k files being referred to as
space-fsLR32k (or MNIfsLR32k) than greyord91k... with the rest of the info
specified in the .json...

You have the most experience with CIFTI files and I trust your intuition. How are those files named in HCP outputs?

**Comment by edickie** [comment]
>
> You have the most experience with CIFTI files and I trust your intuition.
> How are those files named in HCP outputs?


 `*Atlas_s{fwhm}.dtseries.nii`, which *nobody* understands..(they,
essentially, leave all the space into to xml header and make users figure
it out for themselves). A BIDS Common Derivatives spec will be a big help
for users.

**Comment by chrisgorgo** [comment]
Indeed this name is not very intuitive.

So to clarify - we are not debating the definition of the hybrid space

> Combination of `MNI152NLin6AsymConte69` subcortical volumetric space (with 2mm grid) and `fsLR32k` surface space resulting in 91282 data points. Used in Human Connectom Project. [https://github.com/Washington-University/HCPpipelines/tree/master/global/templates/91282_Greyordinates](https://github.com/Washington-University/HCPpipelines/tree/master/global/templates/91282_Greyordinates)

, but its name. Here are the options:

- `grayord91k`
- `fsLR32k`
- `MNIfsLR32k`

Which one people like the most? Please mind that `fsLR32k` is already a name of a pure surface space.

**Comment by edickie** [comment]
fsLR32kgreyord ?

**Review by edickie — CHANGES_REQUESTED** [review]
Sorry couldn't figure out where else to comment..

We can add fsLR4k (the space for HCP MEG analysis)

We could also add a note in the table that:
fsLR4k -> used by HCP pipelines for MEG analysis
fsLR32k ->  used by HCP pipelines for 3T MRI bold and DWI analysis
fsLR59k -> used by HCP pipelines for 7T MRI bold and DWI analysis
fsLR164k -> used by HCP pipelines for 3T and 7T anatomical analysis

**Comment by satra** [comment]
grey is very gray !

my preference for now would be `MNIfsLR32k` - makes it very explicit.

a quick side note: if we are allowing resolution via number of vertices here but not for MNI spaces (voxel size), is there a particular reason that's more pertinent/important? i think that should be clarified in the description.  i.e. if there is a way to map from fsLR164 to fsLR32 then that is similar to going from MNI 1mm to 2mm, but we don't differentiate those. in freesurfer, there is a mapping from fsaverage to all the smaller surfaces.

**Comment by edickie** [comment]
Thanks Satra! MNIfsLR32k is indeed the most explicit. It also maps back to
the HCP filename best (where spaces are implied by the folder name
MNINonLinear/fsaverage_LR32k).

It's (according to Matt Glasser) rather straightforward to map from 164k to
32k with `wb_command -cifti-resample`. The one reason for having the mesh
resolution in the `space-` key is to disambiguate between 164k and 32k data
in HCP pipeline outputs. Although we could bring back the `res-` key-value
pair for that?

**Comment by chrisgorgo** [comment]
@edickie I made the requested changes
@satra I changed the name

> a quick side note: if we are allowing resolution via number of vertices here but not for MNI spaces (voxel size), is there a particular reason that's more pertinent/important? i think that should be clarified in the description. i.e. if there is a way to map from fsLR164 to fsLR32 then that is similar to going from MNI 1mm to 2mm, but we don't differentiate those. in freesurfer, there is a mapping from fsaverage to all the smaller surfaces.

Indeed this inconsistency does exist and has been present for other surface spaces. I think this started because resampling surfaces was harder or less intuitive. If you could propose a clarification in the description as a PR that would be wonderful.

**Comment by coalsont** [comment]
> I dunno. There's still some issues.
> 
> 1. Gifti files in hcp outputs have both volume and surface spaces (I.e. there are both T1w/32k meshes and MNI/32k meshes in HCP derivatives).
> 2. The fact that the fsLR32k surfaces should. Be used with the greyordinate91k files is less intuitive.
> 3. If "greyordinate" is a lot of characters. If we do go in this direction I'm in favor or condensing it -'greyord'?
> 
> Also I think fsLR32k might be different (ish) from Conte69...but I'll look it up tomorrow.

Clarification: of our gifti files, only surface geometry files (.surf.gii) contain coordinates, and therefore are directly attached to a coordinate space, other HCP gifti files do not contain coordinates.  Some of our other gifti files are made using the coordinate information, and could be said to be indirectly attached to that anatomical space, and others have gone through processing that uses some of the coordinate information (for instance, for calculating distances during gradient or smoothing - using a MNI space surface instead of a T1w space surface changes distances slightly).

Cifti files do not contain surface coordinate information, but the vertex-based data in them could similarly be indirectly linked to a particular coordinate space by processing steps (our 91k grayordinate space does not specify how the surface data should be processed, but the voxel-based data is specified to be in MNI space).  It is possible to make a connectivity file that uses different mappings for rows and columns, which in turn could actually contain different volume spaces, but I don't know of anyone who has done this.

Our 91282 grayordinate space is more specific than just "2mm MNI voxels and fsLR32k vertices", it also specifies exactly what vertices/voxels are to be used in each structure, and how they are ordered in the cifti file.  It is possible (in several ways) to make an incompatible cifti grayordinate space using 2mm MNI voxels and fsLR32k vertices.  Thus, there might be a future issue if the name is made of only "MNI" and "fsLR32k".  You could tack "HCP" and/or "91k" onto the name to solve this (or call it something like "gray91k" for shortness and document all that that entails somewhere).

Conte69 is a particular dataset, while fsLR32k is a surface mesh.  Some of the Conte69 files are provided on the fsLR32k mesh.

**Comment by chrisgorgo** [comment]
Thanks, @coalsont. I think the definitions are specific enough (see https://github.com/chrisfilo/bids-specification/pull/5/files#diff-546d0855a542bcec77412f277dd302aeR195), but we are debating the name to find something specific and intuitive enough. `gray91k` was not conveying the link to `fsLR32k` so this is why we went for `MNIfsLR32k`, but maybe we should follow your suggestion and go for `HCPMNIfsLR32k`. What do you think @edickie?

**Comment by edickie** [comment]
Thanks for chiming in @coalsont! 

re: gifti files. It's true that I was only thinking about the `surf.gii` gifti files. We are recommending anatomical section that all other types of data be stored as CIFTI (i.e. `dtseries.nii` are preferable to `func.gii` and `.dscalar.nii` are prefereble to `.shape.gii`) So `.surf.gii` are the only ones that I'm worried about describing in the spec. But maybe this should be restated elsewhere for clarity?

I'm cool about adding `HCPMNIfsLR32k` to clarify that the subcortical data maps to HCP structures according to the HCP atlas ROIs at in https://github.com/Washington-University/HCPpipelines/blob/master/global/templates/91282_Greyordinates/Atlas_ROIs.2.nii.gz. 
or better https://github.com/templateflow/tpl-fsLR/blob/master/tpl-fsLR_res-02_desc-aseg_dseg.nii.gz ?  

@oesteban are https://github.com/Washington-University/HCPpipelines/blob/master/global/templates/91282_Greyordinates/Atlas_ROIs.2.nii.gz and https://github.com/templateflow/tpl-fsLR/blob/master/tpl-fsLR_res-02_desc-aseg_dseg.nii.gz the same files?

**Comment by coalsont** [comment]
This may be off in the weeds, but there actually are a few specialized files that I recommend leaving as gifti, mainly the vertex area files used for resampling and for area loss correction when using group average surfaces (because masking them with the medial wall ROI is a bad idea for some purposes).

**Comment by coalsont** [comment]
I would suggest pointing to the HCP repo for the definition of the HCP grayordinates space.

**Comment by chrisgorgo** [comment]
Like so https://github.com/chrisfilo/bids-specification/pull/5/files#diff-546d0855a542bcec77412f277dd302aeR195 or did you have something else in mind?

**Comment by coalsont** [comment]
Those links look fine (though the identifier hasn't been changed as discussed), I was intending to respond to @edickie suggesting links to templateflow/tpl-fsLR.

**Comment by edickie** [comment]
Good points @coalsont !

Also, I'm noticing now that my recommendation to leave things like cortical thickness in CIFTI only did get removed. So better explanation that `*.func.gii`, `*.shape.gii`, and `*label.gii` files do not have a "volume" space might be better warranted.

Definitely would love your input on templateflow. Also, [this spreadsheet](https://docs.google.com/spreadsheets/d/1uJKQWoqGFD0FJE8Tm9hQVFj2-xOgo5zN1dO-ALwkT0M/edit#gid=0) where I'm trying to map the ciftify outputs according to this spec.

**Pull request merged**
