### PR TITLE
[WIP - not ready for review] Updates to decision making

### PR DESCRIPTION
**Pull request by KirstieJane**
Opening this as I develop - not ready for review!

* Added more explanation of the CODEOWNERS file as a comment in the file itself and in the CONTRIBUTING guidelines
* Made a few formatting changes to the CONTRIBUTING guidelines that aren't very relevent to this PR (I can pull those out and put them in a different one if that would make it easier to review)

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Hey - it would be great if you could limit the suggestions to issues strictly related to the original PR (decision making). It will make the whole thing easier to review and will avoid prologing the already very long discussion. The other suggestions in this WIP PR look very nice, but should probably be part of another PR.

**Comment by KirstieJane** [comment]
Hey @chrisfilo - just a little note that I got to 2am and hen needed to go to bed 😱😱😱

I have a sprint today and tomorrow so I’m not 100% sure if I can get the next bit of the suggestion uploaded but I’ll try - please nudge me on Thursday if I haven’t commented on  the main PR.

**Comment by chrisgorgo** [comment]
Thanks.
I see you went with a full rewrite of the decision making rules - it's probably most appropriate to open open a new PR against bids-standart/bids-specification.

I also feel that it would be essentially for your PR to list all of the initial core contributors and maintainers, and make sure they agree on their new responsibilities.

**Comment by KirstieJane** [comment]
Hey @chrisfilo. I’ll close this PR. I do want to note that it explicitly says that it is *not* ready for review. I don’t think I’ll open another at this time.

**Pull request closed without merging**
